services:
  - type: web
    runtime: node
    name: baatein-games-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://gamesbaatein-frontend.vercel.app
